import type { Job } from "./types";

const daysAgo = (n: number) =>
  new Date(Date.now() - n * 86_400_000).toISOString();

/**
 * Sample postings so the dashboard is usable before you wire up API keys, and
 * so it still renders when a source is unreachable. Replaced by live data on
 * the first successful run.
 */
export const SEED_JOBS: Job[] = [
  {
    id: "seed-1",
    title: "Principal Software Engineer, Integration Platform",
    company: "Northwind Cloud",
    location: "Bengaluru, India (Hybrid)",
    market: ["india"],
    remote: false,
    url: "https://example.com/jobs/northwind-principal",
    source: "Seed",
    postedAt: daysAgo(1),
    fetchedAt: daysAgo(0),
    description:
      "We are hiring a Principal Software Engineer to lead our integration platform. You will own Apache Airflow based ETL orchestration, design multi-tenant connector frameworks, and drive API platform strategy. Deep Python and AWS experience required (EKS, Aurora, Boto3). Experience with SAP, Salesforce or ERP integration is a strong plus. You will mentor senior engineers and set architecture direction across teams.",
    tags: ["python", "airflow", "aws", "integration"],
    salary: "₹70–90L",
    stage: "matched",
    stageUpdatedAt: daysAgo(1),
  },
  {
    id: "seed-2",
    title: "Staff Engineer, Data Platform",
    company: "Meridian Labs",
    location: "Remote (US) — visa sponsorship available",
    market: ["us", "remote"],
    remote: true,
    url: "https://example.com/jobs/meridian-staff",
    source: "Seed",
    postedAt: daysAgo(3),
    fetchedAt: daysAgo(0),
    description:
      "Staff Engineer to scale our data platform. Airflow, dbt, Snowflake and Kafka in production. You will design event-driven pipelines, own observability, and partner with product teams on API design. Strong Python and Kubernetes required. Relocation and visa sponsorship available for exceptional candidates. Distributed systems experience expected.",
    tags: ["airflow", "kafka", "snowflake", "kubernetes"],
    salary: "$210k–$260k",
    stage: "matched",
    stageUpdatedAt: daysAgo(3),
  },
  {
    id: "seed-3",
    title: "Senior Software Engineer — Backend",
    company: "Tessellate",
    location: "Hyderabad, India",
    market: ["india"],
    remote: false,
    url: "https://example.com/jobs/tessellate-senior",
    source: "Seed",
    postedAt: daysAgo(6),
    fetchedAt: daysAgo(0),
    description:
      "Backend engineer for our B2B SaaS product. Python, PostgreSQL, REST API design, CI/CD. You will build third-party integrations and webhooks. Some exposure to microservices and Docker expected.",
    tags: ["python", "postgresql", "api"],
    stage: "matched",
    stageUpdatedAt: daysAgo(6),
  },
  {
    id: "seed-4",
    title: "Principal Architect, Enterprise Middleware",
    company: "Corvus Systems",
    location: "Remote (India or EU)",
    market: ["india", "remote"],
    remote: true,
    url: "https://example.com/jobs/corvus-architect",
    source: "Seed",
    postedAt: daysAgo(2),
    fetchedAt: daysAgo(0),
    description:
      "Own the architecture of our enterprise middleware / iPaaS offering. SAP Cloud Integration, SuccessFactors, OAuth2, SAML, connector SDKs. Airflow orchestration at multi-region scale. You will lead compliance work including FIPS and SOC 2, and represent architecture to enterprise customers. Python and TypeScript.",
    tags: ["sap", "ipaas", "oauth2", "airflow", "compliance"],
    stage: "queued",
    stageUpdatedAt: daysAgo(1),
  },
  {
    id: "seed-5",
    title: "Engineering Manager, Platform",
    company: "Halcyon",
    location: "Bengaluru, India",
    market: ["india"],
    remote: false,
    url: "https://example.com/jobs/halcyon-em",
    source: "Seed",
    postedAt: daysAgo(4),
    fetchedAt: daysAgo(0),
    description:
      "Engineering Manager to lead a platform team of 8. You will own hiring, performance and roadmap. Prior hands-on Python and AWS experience expected but this is a people-management role.",
    tags: ["management", "python", "aws"],
    stage: "matched",
    stageUpdatedAt: daysAgo(4),
  },
  {
    id: "seed-6",
    title: "Staff Software Engineer, Developer Platform",
    company: "Lumen Grid",
    location: "Austin, TX, United States",
    market: ["us"],
    remote: false,
    url: "https://example.com/jobs/lumengrid-staff",
    source: "Seed",
    postedAt: daysAgo(9),
    fetchedAt: daysAgo(0),
    description:
      "Staff engineer on our developer platform. Kubernetes, Terraform, Go and Python. You will build internal tooling, CI/CD, and observability for 200+ engineers. Must be authorized to work in the US.",
    tags: ["kubernetes", "terraform", "go"],
    salary: "$200k–$240k",
    stage: "matched",
    stageUpdatedAt: daysAgo(9),
  },
  {
    id: "seed-7",
    title: "Junior Python Developer",
    company: "Bytewise",
    location: "Pune, India",
    market: ["india"],
    remote: false,
    url: "https://example.com/jobs/bytewise-junior",
    source: "Seed",
    postedAt: daysAgo(5),
    fetchedAt: daysAgo(0),
    description:
      "Entry level Python developer. 0–2 years experience. Learn REST APIs and SQL in a supportive team.",
    tags: ["python", "sql"],
    stage: "matched",
    stageUpdatedAt: daysAgo(5),
  },
  {
    id: "seed-8",
    title: "Principal Engineer, Cloud Integrations",
    company: "Ardent ERP",
    location: "Remote (Global)",
    market: ["remote", "india", "us"],
    remote: true,
    url: "https://example.com/jobs/ardent-principal",
    source: "Seed",
    postedAt: daysAgo(0),
    fetchedAt: daysAgo(0),
    description:
      "Principal engineer for cloud ERP integrations. You will architect connector frameworks across SAP, Salesforce, QuickBooks and NetSuite, own Airflow based orchestration on AWS EKS, and drive OAuth2 auth patterns. Multi-region deployments, Aurora, Boto3. Enterprise SaaS, multi-tenant, scalability. Relocation supported.",
    tags: ["sap", "salesforce", "quickbooks", "airflow", "aws", "eks"],
    salary: "Competitive",
    stage: "applied",
    stageUpdatedAt: daysAgo(0),
  },
];
